### ISSUE TITLE
i don't know how to Run script

### ISSUE THREAD

**Issue by ghost** [mtve/yazecminer#12]
hi 
i already download you file : js-backend ,
i want run in my website,
but my website just making out by html and javascript
website in the cpanel host 
i just know a little html and javascript and css
and i already setting the server.pl
but i don't know how to run the server.pl
i very wish you can help me 
thank you

**Comment by mtve** [comment]
i recommend you to start with simple setup, just to understand how the things work.

you will need some unix system with perl.

1) checkout all repository (git clone ...)
2) change directory to `js-backend/ `
3) run
`perl server.pl`
4) open page http://127.0.0.1:8888 in your browser
5) see how mining has started

if everything is fine, explore how it works - how the page opens websocket, how miner core gets jobs, what is written to logs etc 

then, if you want to go further and provide some service, plan your production setup, maybe some proxies and so on.

**Comment by ghost** [comment]
hi mtve 
thank for your help

i can run this 
but now have a new problem
the mining pool is zcash.flypool.org
i had runing 1h 
but i go to http://zcash.flypool.org see my works is zero...

this is my setting

my %CFG = (
	LOG_FILE		=> 'log/server.log',
	LOG_LEVEL		=> 'debug',

	STAT_INTERVAL		=> 5 * 60,
	STAT_SHOW_CLIENT	=> 5,
	STAT_SHOW_BEST		=> 5,
	STAT_SHOW_BAN		=> 5,

	HTTP_ADDR		=> '0.0.0.0',
	HTTP_PORT		=> 8888,
	HTTP_CLIENT_TIMEOUT	=> 60,
	HTTP_HIDDEN_ADMIN_PAGE	=> 'admin',
	HTTP_WS_PING_INTERVAL	=> 30,

	POOL_HOST		=> 'asia1-zcash.flypool.org',
	POOL_PORT		=> 3333,
	POOL_WORKER_NAME	=> 't1Hzq76qZRZHkuSBkxM1rDuWCCWFSzKXZRG.js',
	POOL_WORKER_PASS	=> 'x',
	POOL_KEEP_INTERVAL	=> 1 * 60,
	POOL_SESSION_TIMEOUT	=> 10 * 60,
	POOL_MINER_NAME		=> 'jazecminer',
);

maybe you can see and tell me what is my erreo
again thank you very much

**Comment by mtve** [comment]
one hour is a very small time with current network difficulty and small number (perhaps one?) of miners.

wait for a few hours at least.

also, flypool statistics maybe lagging, it can update after some delay.

**Comment by mtve** [comment]
i'm going to close this issue, feel free to ask any questions.

**Comment by ghost** [comment]
hi mtve
thank for your help

i again run the page have one night 
i discover the item [submitted] always is zero
but other item is have the quantity
you think it is normal?

and my computer system is window 7
it will be problem?

i am sorry about that because i am stupid 
T_T

**Comment by mtve** [comment]
i will close this issue since we're already talking in another one #13
