### ISSUE TITLE
the item [submitted] always is zero

### ISSUE THREAD

**Issue by ghost** [mtve/yazecminer#13]
hi mtve
thank for your help

i again run the page have one night 
i discover the item [submitted] always is zero
but other item is have the quantity
you think it is normal?

and my computer system is window 7
it will be problem?

i am sorry about that because i am stupid 
T_T

**Comment by mtve** [comment]
if "solutions count" number and other counters are ticking and "submitted" stays zero for a very long time, it's not good.

windows 7 should not be a problem, but the browser could be.   what is your browser?

approximate number of submitted solutions is like total number of solutions divided by difficulty (for example for flypool's target like 0x00081893... difficulty will be more then 8100).

so to submit one good solution you must find on average more then 8100 total solutions.   it's a matter of luck of course, but even for extremely bad luck it should be no more than 15000 solutions i'd say.

other than that, it's hard to diagnose what's wrong.   you may try to mine at http://frox25.no-ip.org:8888 which is known to work.    read the server.pl logs and browser console output.

**Comment by ghost** [comment]
hi mtve
my browser is google chrome

**Comment by ghost** [comment]
if you not mind ,i can donate for you?
if can ,this is how much? 
would you help me setup in the website and other setting? 
i want the function is a web page ,all people goto this page will auto mining and pay for my wallet

**Comment by mtve** [comment]
thanks, no need for donations.

i would suggest you to calculate a business case first.    the mining is hard process and your profit will depend on the number of miners.    as a rough estimation, if you can make 50 people sit around the site 24 hours a day, you will earn about $1 a month.    it's not 50 page hits a day, it's not daily visitors, it's browsers that watching your page all day round without interruptions.  if it will be just some random site with cats or news and average watching time is 1 minute - you will need 50 * 24 * 60 = 72000 visitors.    are you sure you will be able to attract this number of users?     btw if you can now, you can already make around the same amount of money with some advertising network.

and if you're going to make a business, you need some technical help, and unfortunately i can't help with administration and maintenance.   you better find and hire some technician.

**Comment by ghost** [comment]
very thank you 
you recommend is good
i need calculate the cost

and i both not very know this 
i think i need restudy

thank your reply

**Comment by mtve** [comment]
you're welcome!  i'm closing this issue, but feel free to ask any questions in this or new issue.
