### ISSUE TITLE
Reduce the memory usage when mining...

### ISSUE THREAD

**Issue by superdcc** [mtve/yazecminer#14]
Hi Mtve, Awesome project...Thank you again & again...
I deep in your project & Equihash algorithm couple day.

And i find the problem is: when mining, the memory cost too much...
this cause the Browser will lag regularly...

So may you tell me, if it possible to Reduce the memory when mining?
I know the algorithm is ASIC resisten, So this situation is normal...

But we are mining in browser not native...
is it  possible optimize the original C, and let the webassembly better?
Or should i try optimize the webassembly side ?

Thank you^^

*I use the chrome Devtool... they detect the miner cost memory about 220MB

**Comment by mtve** [comment]
Hello!   220MB seems pretty correct.    C version should show the same.

the theoretical memory minimum for equihash algorithm with zcash parameters is 144MB but it requires serious optimizations and possible performance trade off.

you may of course try to optimize it, interesting forks and patches are very welcome.

**Comment by mtve** [comment]
i'm closing this issue, feel free to ask any questions.

**Comment by superdcc** [comment]
Thanks mtve ^^

I read the code & find any way to optimization it...
but I am not good a low level language... so this way still fighting...

1. If I want to do performance trade off, the way is store the variable to Hard Drive rather then Memory?

2. I want to build a website like Coin-Hive, but use zcash...
    Is it possible use equihash algorithm mining without lag?

    Maybe I use the C++ version to try?
    Or is my idea is possible "working"   ><""  ?

**Comment by mtve** [comment]
1. well, according to http://norvig.com/21-days.html#answers it could be 100 or more times slower.

2. it's surely possible to build CoinHive analog, it needs some payments infrastructure, but the core miner is almost complete (you may need fallback to pure js in addition to existing webassembly).    would you please explain "without lag"?   

C++ is upward compatible with C, so you may try to compile C version of miner with C++, however it should not speed up the thing.

**Comment by superdcc** [comment]
I change the main loop to 10 sec or 5 sec.
the browser will temporary stop(1.5 sec or 2 sec) when the browser actually execute mine algorithm....

that I call "lag"... May I know some way to test & get rid off this?



the other infrastructure part I don't think is key & problem^^
thank you for your soon reply^^

**Comment by mtve** [comment]
got it.       to reduce lags you can insert some delay between algorithm steps, or you can put miner inside Web Worker ( https://www.w3schools.com/HTML/html5_webworkers.asp ) as CoinHive does (i believe).
