### ISSUE TITLE
Error when start yazecminer

### ISSUE THREAD

**Issue by mazetuski** [mtve/yazecminer#15]
Websocket always stay in opening and change to error
I am getting this in server.log when enter in localhost:8888 after perl server.pl

![imagen](https://user-images.githubusercontent.com/11924094/33844597-042ddc06-dea1-11e7-85e0-bdc9b0fa4d25.png)

**Comment by mazetuski** [comment]
I just see that in chrome I work correctly, this error gives me in mozilla

Firefox 57 (Quantum)

**Comment by mtve** [comment]
i guess you have too many cookies for localhost (127.0.0.1), you may try to delete all cookies before connecting.

will investigate tomorrow, anyway it's time to update perl modules.

**Comment by mazetuski** [comment]
It works thanks!
Another question: is it possible to increase the use of the user's CPU without opening more tabs? When I use it only uses 20% of the CPU

**Comment by mtve** [comment]
great, so i will not patch it.   in case you really need to work with big cookies, you may increase number on this line:
   https://github.com/mtve/yazecminer/blob/master/js-backend/lib/Protocol/WebSocket/Message.pm#L24

on another question: the miner uses only one cpu core now.    the code on the main page needs to be rewritten as separate module, and then started in "Web Workers".      so, yes, it's possible, but not with current code.
