### ISSUE TITLE
Is possible to connect with Nicehash stratum?

### ISSUE THREAD

**Issue by mazetuski** [mtve/yazecminer#16]
i saw #1 but with stratum.zcash.nicehash.com:3357 always error and with stratum+tcp..
![imagen](https://user-images.githubusercontent.com/11924094/34294296-1cae7b54-e708-11e7-9f9b-8b34e7cc9eb8.png)
![imagen](https://user-images.githubusercontent.com/11924094/34294286-0f5fc23c-e708-11e7-93c3-0fa7bab77c79.png)

**Comment by mtve** [comment]
i'm unable to connect to that address and port right now, cloudflare gives me error 502 (something's wrong on the nicehash side)

however it should be possible to connect without that "stratum+tcp://" part, just hostname in `POOL_HOST` and port in `POOL_PORT`

**Comment by mtve** [comment]
site is up now, but i can't connect to a pool.

i can't find any details on their site and i'm not sure their "equihash" means zcash at all.

there is no enough information at https://github.com/nicehash/Specifications on any other places i've found.

so, for now - no, unfortunately we're not compatible with nicehash.
