### ISSUE TITLE
Understanding the config and tweaks

### ISSUE THREAD

**Issue by rymdluo** [mtve/yazecminer#2]
I gave the compiled files a run at it and I was able to set it up pretty easily. I do have some questions about the configuration that's passing me by:

What to these values refer too?
```
POOL_KEEP_INTERVAL	=> 1 * 60,
POOL_SESSION_TIMEOUT	=> 10 * 60,
```

How would I go about changing the number of threads and ram usage?

**Comment by rymdluo** [comment]
I was reading up the code and found this, which seems like the bit.
```
EMCC	+= -s TOTAL_MEMORY=256MB
```

I also found out that pThreads/multithreading isn't ready for WebAssembly yet. So I think what you meant by multithreading was by using concurrent webworkers?

**Comment by mtve** [comment]
POOL_KEEP_INTERVAL is the number of seconds for periodic timer, which triggers reconnect to mining pool if connection was not up for any reasons.

POOL_SESSION_TIMEOUT is mining pool connection inactivity timeout, if nothing happens during this time the session will be disconnected, it's a protection for network freezes.

there is no threads at all.   server side (backend) is event-driven single thread single process, client side is javascript (webassembly) which is also like single thread.     i can't find mentioning of "thread" in this project, would you please clarify where did you get it, so maybe i will fix the docs to avoid any confusion?

you can change ram usage of client by changing that Makefile line indeed, but minimum required size is above 200MB, so 256MB is just a round up.    good news is that the ram usage is static, so it will either work normally or fail soon.

**Comment by rymdluo** [comment]
There wasn't, I was alluded to it being possible by the phrasing below.
```
It's single-threaded on purpose
```

Thanks for your explanation.
