### ISSUE TITLE
Mining in browser

### ISSUE THREAD

**Issue by walruzperil** [mtve/yazecminer#3]
Hello, thanks for greade work. Can you explain, i see in static folder js miner. How i can use it. If run index.html in concole i see (index):54 WebSocket connection to 'ws://mysite.com/ws' failed: Error during WebSocket handshake: Unexpected response code: 404.
thanks

**Comment by walruzperil** [comment]
wow i see need AnyEvent and Protocol::WebSocket: 
how i can install in on ubuntu?

**Comment by mtve** [comment]
you need to run perl script server.pl that works as a webserver, serving static files from /static folder and websocket for mining.

you don't need to install these modules, it's optional.

**Comment by walruzperil** [comment]
its runing now, thank you. It possible make same miner for cryptonight algo?

**Comment by walruzperil** [comment]
and why you use POOL_WORKER_NAME	=> 't1Vm6PbF2ZkSLshWHKwLqxD7oU6TgEDX5nV.js',
dot js?

**Comment by mtve** [comment]
> It possible make same miner for cryptonight algo?

yes, i think it's possible.

> why you use .js

just to see different instances as separate miners on the same wallet, it's flypool's notation.

**Comment by walruzperil** [comment]
Thank you. I will wait cryptonight js miner. :) Zec is not very suitable for CPU...
