### ISSUE TITLE
Cryptonight miner

### ISSUE THREAD

**Issue by walruzperil** [mtve/yazecminer#5]
Hello, do you planing make the same miner for cryptonight currency? thx

**Comment by mtve** [comment]
Nope, sorry.   It's interesting but I have not enough time.

**Comment by walruzperil** [comment]
Vary sad.

**Comment by walruzperil** [comment]
Может есть интерес за денюшку сделать, готов заплатить 15к руб... :)

**Comment by mtve** [comment]
I can not promise anything.   If someday I do it, then I will come back to you and ask for 1 ZEC.

**Comment by walruzperil** [comment]
Hello, you still no try made Cryptonight wasm miner?

**Comment by mtve** [comment]
nope

**Comment by walruzperil** [comment]
You do not know how to do this? Or there is no time? I'm ready to pay you 1.5 ZEC ...

**Comment by mtve** [comment]
Unfortunately no time.

**Comment by mtve** [comment]
Hi!    have you seen https://coin-hive.com/ ?

**Comment by walruzperil** [comment]
wow, thanks for sharing it

**Comment by walruzperil** [comment]
nice site with good hashrate. but they pay only 70% of mine. :)

**Comment by mtve** [comment]
"Well, nobody's perfect"
